version: "3.1"
services:
  nacos:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      #- NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - backend
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: seata
      MYSQL_USER: demo
      MYSQL_PASSWORD: demopass
    volumes:
      - ./script/seata-tc-server.sql:/docker-entrypoint-initdb.d/seata-tc-server.sql
      - mysql4seata_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
  seata-server:
    image: apache/seata-server:2.1.0-slim
    ports:
      - 8091:8091
      - 7091:7091
    volumes:
      # - ./libs/mysql-connector-java-8.0.19.jar:/seata-server/libs/jdbc/mysql-connector-java-8.0.19.jar
      - ./libs/mysql-connector-java-8.0.19.jar:/seata-server/libs/mysql-connector-java-8.0.19.jar
      - ./conf/application.yml:/seata-server/resources/application.yml
    networks:
      - backend
    depends_on:
      - mysql
volumes:
  mysql4seata_data:

networks:
  backend:
    driver: bridge